# Generated by Django 5.2 on 2025-05-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingMinutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('location', models.CharField()),
                ('agenda', models.CharField()),
                ('discussion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'MeetingMinutes',
            },
        ),
    ]
