# Generated by Django 5.2 on 2025-05-08 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingminutes',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meetingminutes',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
