# Generated by Django 5.2 on 2025-05-11 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_meetingminutes_end_time_meetingminutes_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingminutes',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='meetingminutes',
            name='co_hosts',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='meetingminutes',
            name='guests',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meetingminutes',
            name='hosts',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='meetingminutes',
            name='total_attendees',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meetingminutes',
            name='written_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
